Repository nextcloud/groupfolders, pull requests merged in 2020-10, with the labels that each got.

#1063 syntax fix: added space between group and folder
  src/components/SharingSidebarView.vue
Labels: 3. to review

#1064 OCC command to empty the trashbin
  appinfo/info.xml
  lib/Command/Trashbin/Cleanup.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
Labels: 3. to review, backport-request, enhancement

#1070 Load files client extension through file list plugin
  src/client.js
  src/files.js
Labels: 3. to review, bug
