Repository nextcloud/groupfolders, pull requests merged in 2020-04, with the labels that each got.

#797 Try to return the owner of the mountpoint before returning no owner
  lib/Mount/GroupFolderStorage.php
  lib/Mount/MountProvider.php
Labels: 3. to review

#843 Check ACL before restoring from the trash bin
  lib/Trash/TrashBackend.php
Labels: 3. to review, bug

#842 Make sure that the target we try to restore to doesn't exist yet
  lib/Trash/TrashBackend.php
Labels: 3. to review

#854 Bump version to 6.0.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#855 Bump version to 5.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#856 Bump version to 4.1.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#860 Bump version to 6.0.5
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review, release

#884 Use a lazy folder
  lib/AppInfo/Application.php
  lib/Helper/LazyFolder.php
Labels: 3. to review, enhancement

#887 Bump version to 6.0.6
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review, release
