Repository nextcloud/groupfolders, pull requests merged in 2020-03, with the labels that each got.

#790 Bump version to 6.0.2
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review, release

#798 Exclude files that are not needed from build
  Makefile
Labels: 3. to review, backport-request, bug

#789 Bump version to 5.0.6
  CHANGELOG.md
  Makefile
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, release

#814 Enhance documentation about applying ACL on top of regular permissions
  README.md
Labels: 3. to review

#830 Fix: Trying to access array offset on value of type int
  lib/Versions/VersionsBackend.php
Labels: 3. to review, bug
