Repository nextcloud/groupfolders, pull requests merged in 2020-08, with the labels that each got.

#984 Properly encode group names as url parameter
  appinfo/routes.php
Labels: 3. to review, bug

#983 Do not fail if no applicable groups are setup
  lib/Folder/FolderManager.php
Labels: 3. to review, bug

#990 Always delete expired versions regardless of the filecache permissions
  lib/Versions/GroupVersionsExpireManager.php
Labels: 3. to review, backport-request, bug

#917 Make files client extension more robust to loading race conditions
  src/client.js
Labels: 4. to release, bug

#1001 [stable18] Release 6.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#1000 [stable17] Release 5.0.8
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#1002 [stable19] Release 7.0.0
  .travis.yml
  CHANGELOG.md
Labels: 3. to review, release

#1015 Remove unused imports
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/Helper/LazyFolder.php
  lib/Migration/Version401001Date20190715092137.php
  lib/Versions/VersionsBackend.php
  tests/ACL/ACLManagerTest.php
Labels: 3. to review, technical debt

#999 Show inherited acls (rebased)
  src/client.js
  src/components/AclStateButton.vue
  src/components/SharingSidebarView.vue
  src/model/Rule.js
Labels: 3. to review, enhancement
