Repository nextcloud/groupfolders, pull requests merged in 2021-08, with the labels that each got.

#1620 Create dependabot-approve-merge.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review

#1630 Correctly calculate directory sizes when using an object store primary storage
  lib/Mount/GroupFolderStorage.php
Labels: bug, 4. to release

#1640 Load groupfolders-files.js instead of files.json
  lib/Listeners/LoadAdditionalScriptsListener.php
Labels: backport-request

#1636 Makefile should use npm to compile javascript and not directly call webpack.
  Makefile
Labels: bug

#1637 Pin mariadb to 10.5
  .github/workflows/phpunit.yml
Labels: backport-request
