Repository nextcloud/groupfolders, pull requests merged in 2021-04, with the labels that each got.

#1366 load all acl rules for a folder/search result in one go
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
Labels: 3. to review, acl

#1389 Update README.md for REST API's
  README.md
Labels: 3. to review

#1406 Sidebar view: refresh ACL entries when fileInfo prop changes #1378
  src/components/SharingSidebarView.vue
Labels: 3. to review

#1395 Fixed searching for groups in the sharing sideview
  lib/Folder/FolderManager.php
  src/components/SharingSidebarView.vue
  src/settings/Api.ts
Labels: 3. to review, search

#1416 Adds github ISSUE TEMPLATES
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3. to review, enhancement

#1351 [stable19] Check for naming conflicts before returning the user mounts
  lib/AppInfo/Application.php
  lib/Mount/MountProvider.php
Labels: 3. to review, bug

#1346 Obtain cacheEntry for created folders and handle errors more gracefully
  lib/Mount/MountProvider.php
Labels: 3. to review, backport-request, bug
