Repository nextcloud/groupfolders, pull requests merged in 2021-06, with the labels that each got.

#1534 Cancel ACL user/group search requests
  package-lock.json
  package.json
  src/components/SharingSidebarView.vue
Labels: 3. to review, bug

#1472 Enforce string for folder id when obtaining the trash folder
  lib/Folder/FolderManager.php
  lib/Trash/TrashBackend.php
Labels: 3. to review, bug

#1524 Fixes parameters name of manageACL REST endpoint
  README.md
Labels: 3. to review, documentation

#1560 Move to shared js build configs
  .babelrc.js
  .eslintrc.js
  .github/workflows/node.yml
  package-lock.json
  package.json
  src/BinaryTools.js
  src/SharingSidebarApp.js
  src/client.js
  src/components/AclStateButton.vue
  src/components/SharingSidebarView.vue
  src/files.js
  src/model/Properties.js
  src/model/Rule.js
  src/settings/App.css
  src/settings/App.scss
  src/settings/App.tsx
  src/settings/EditSelect.css
  src/settings/EditSelect.scss
  src/settings/FolderGroups.css
  src/settings/FolderGroups.scss
  src/settings/FolderGroups.tsx
  src/settings/QuotaSelect.tsx
  stylelint.config.js
  webpack.dev.config.js
  webpack.js
  webpack.prod.config.js
Labels: 3. to review, technical debt

#1566 Fixes build system after changes introduced by 704edc3fab11077fae13b5214271d07862c0f823
  Makefile
  package.json
  templates/index.php
Labels: 3. to review, bug
