Repository nextcloud/groupfolders, pull requests merged in 2021-11, with the labels that each got.

#1748 Only execute on PRs or pushes to protected branches
  .github/workflows/static-analysis.yml
Labels: 4. to release

#1753 Enfore the usage of int for quota
  lib/Folder/FolderManager.php
  lib/Versions/GroupVersionsExpireManager.php
Labels: backport-request, 3. to review

#1722 Implement Admin delegation for group folder
  appinfo/routes.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/Folder/FolderManager.php
  lib/Settings/Admin.php
  src/settings/Api.ts
Labels: 3. to review

#1759 Expire group folders trashbin
  README.md
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/Command/ExpireGroupVersions.php
  lib/Folder/FolderManager.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  tests/psalm-baseline.xml
Labels: pending documentation, 3. to review, feature: trashbin

#1776 Switch to setup-php@v2 (v1 is deprecated)
  .github/workflows/phpunit.yml
Labels: backport-request

#1772 README.md: Add section 'references' and include links to app store and release notes
  README.md
Labels: enhancement, 3. to review, documentation
