Repository nextcloud/groupfolders, pull requests merged in 2021-02, with the labels that each got.

#1274 Fix output path for chunks
  src/files.js
Labels: backport-request

#1224 Fix file drop shared folders
  lib/ACL/ACLCacheWrapper.php
Labels: 3. to review, backport-request, bug

#1310 Update psalm baseline
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  tests/psalm-baseline.xml
Labels: 3. to review

#1263 check folder permissions when restoring a trashbin item
  lib/Folder/FolderManager.php
  lib/Trash/TrashBackend.php
  tests/Folder/FolderManagerTest.php
Labels: 3. to review, backport-request
