Repository nextcloud/groupfolders, pull requests merged in 2021-03, with the labels that each got.

#1331 Add tooltip for user/group name in sidebar ACL list
  src/components/SharingSidebarView.vue
Labels: 3. to review, backport-request, bug

#1335 Fix "contenthash" not included in chunk filename
  webpack.dev.config.js
  webpack.prod.config.js
Labels: 3. to review, backport-request, bug

#1318 Fix #801 Folder icon in shared group folder
  lib/AppInfo/Application.php
  src/files.js
  tests/psalm-baseline.xml
Labels: 3. to review, bug

#1340 Cast groupfolder id to string when trying to create a new folder
  lib/Mount/MountProvider.php
Labels: 3. to review, backport-request, bug

#1239 Check for naming conflicts before returning the user mounts
  lib/AppInfo/Application.php
  lib/Mount/MountProvider.php
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request

#1334 Fix deletion failing even if there's an entry in the folder listing
  lib/Command/Group.php
Labels: backport-request, bug

#1360 Make clear arguments are ids and not names
  README.md
Labels: 3. to review, bug

#1364 fix ACL error: user can not manage acl even assigned in setting
  lib/Folder/FolderManager.php
Labels: 3. to review, acl

#1388 Fixes some typo in README.md
  README.md
Labels: 3. to review

#1374 preventDefault on folder create submit event
  src/settings/App.tsx
Labels: 3. to review, backport-request

#1375 fix wrong method call to check restore permissions
  lib/Trash/TrashBackend.php
Labels: 3. to review, backport-request

#1350 [stable20] Check for naming conflicts before returning the user mounts
  lib/AppInfo/Application.php
  lib/Mount/MountProvider.php
Labels: 3. to review, bug

#1380 add hint for subfolder groupfolders to readme
  README.md
Labels: 3. to review
