Repository nextcloud/groupfolders, pull requests merged in 2021-12, with the labels that each got.

#1793 Cast argument from string to int
  lib/Command/Scan.php
Labels: bug, feature: occ

#1792 Fix wrong import in the ExpireGroupVersion job
  lib/BackgroundJob/ExpireGroupVersions.php
Labels: bug, backport-request, 3. to review, feature: trashbin

#1799 Fix OCP\Constant not found
  lib/Versions/VersionsBackend.php
Labels: bug, 3. to review

#1747 Update npm and node engines versions
  package.json
Labels: dependencies

#1823 Unify folder retrival in commands
  lib/Command/ACL.php
  lib/Command/Create.php
  lib/Command/Delete.php
  lib/Command/FolderCommand.php
  lib/Command/Group.php
  lib/Command/Quota.php
  lib/Command/Rename.php
  lib/Command/Scan.php
  tests/psalm-baseline.xml
Labels: 3. to review

#1828 $folder['permissions'] is always null
  lib/Command/ACL.php
Labels: 3. to review

#1842 Fix non user avatars in sharing sidebar
  src/components/SharingSidebarView.vue
Labels: bug, backport-request, 3. to review

#1829 Improve psaml add stub implementation
  lib/ACL/ACLManager.php
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/Rule.php
  lib/ACL/RuleManager.php
  lib/AppInfo/Application.php
  lib/Command/ACL.php
  lib/Command/Scan.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/Folder/FolderManager.php
  lib/Migration/Version103000Date20180806161724.php
  lib/Settings/Section.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  lib/Versions/GroupVersion.php
  lib/Versions/VersionsBackend.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#1845 Allow non admin to use aclMappingSearch
  lib/Controller/FolderController.php
Labels: backport-request, 3. to review
