Repository nextcloud/groupfolders, pull requests merged in 2022-08, with the labels that each got.

#2052 Update npm and node engines versions
  package.json
Labels: dependencies

#2048 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2047 Sort versions in descending order
  lib/Versions/VersionsBackend.php
Labels: bug, backport-request, 3. to review

#2073 Fix folder with hashtag
  src/client.js
Labels: 3. to review
