Repository nextcloud/groupfolders, pull requests merged in 2022-03, with the labels that each got.

#1916 Fix regression with propatch not working
  lib/DAV/ACLPlugin.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: bug, 3. to review, regression

#1923 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1889 set mount provider in mountpoint
  lib/Mount/GroupMountPoint.php
Labels: 2. developing
