Repository nextcloud/groupfolders, pull requests merged in 2022-06, with the labels that each got.

#2013 allow disabling sharing of groupfolder root
  lib/AppInfo/Application.php
  lib/Mount/CacheRootPermissionsMask.php
  lib/Mount/MountProvider.php
  lib/Mount/RootPermissionsMask.php
Labels: 3. to review

#2022 Display group names in occ output
  lib/Command/ListCommand.php
Labels: 3. to review

#2023 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2024 Speedup querying group info
  lib/Controller/DelegationController.php
Labels: backport-request, 3. to review, performance

#2034 Release 12.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#2032 Release 10.0.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
