Repository nextcloud/groupfolders, pull requests merged in 2022-01, with the labels that each got.

#1857 [stable22] Fix double use of the same variable
  lib/Command/ACL.php
Labels: high, 3. to review

#1856 [stable23] Fix double use of the same variable
  lib/Command/ACL.php
Labels: high, 3. to review

#1849 Fix expire commands and background job when trash and/or version apps are disabled
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupPlaceholder.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupBase.php
  lib/Command/ExpireGroup/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
  lib/Trash/TrashBackend.php
Labels: backport-request, 3. to review, regression

#1868 Fix Constant is undefined
  lib/Versions/VersionsBackend.php
Labels: 3. to review

#1869 fix(CLI): Define int type to set folder quota
  lib/Command/Quota.php
Labels: backport-request

#1874 Cleanup ExpireGroupVersions and remove not needed arguments
  lib/BackgroundJob/ExpireGroupVersions.php
Labels: backport-request
