Repository nextcloud/groupfolders, pull requests merged in 2022-04, with the labels that each got.

#1941 Modernize PHP code to php 7.4 standard
  composer.lock
  lib/ACL/ACLManager.php
  lib/ACL/RuleManager.php
  lib/ACL/UserMapping/IUserMapping.php
  lib/ACL/UserMapping/UserMapping.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupPlaceholder.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/CacheListener.php
  lib/Command/ACL.php
  lib/Command/Create.php
  lib/Command/ExpireGroup/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
  lib/Command/FolderCommand.php
  lib/Command/Group.php
  lib/Command/ListCommand.php
  lib/Command/Scan.php
  lib/Command/Trashbin/Cleanup.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/Controller/PageController.php
  lib/DAV/ACLPlugin.php
  lib/Folder/FolderManager.php
  lib/Helper/LazyFolder.php
  lib/Mount/GroupFolderStorage.php
  lib/Mount/MountProvider.php
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 2. developing

#1949 Make property visibility compatible with Wrapper implementation
  lib/Mount/GroupFolderStorage.php
Labels: bug, 3. to review

#1951 Fix expiration when storage is unlimited and auto expiration is on
  lib/Trash/TrashBackend.php
Labels: bug, 3. to review

#1962 Update parent folders cache when restoring files from trash
  lib/Trash/TrashBackend.php
Labels: backport-request, 3. to review, feature: trashbin

#1965 [stable23] Update parent folders cache when restoring files from trash
  lib/Trash/TrashBackend.php
Labels: backport-request, 3. to review, feature: trashbin

#1968 cache and reuse root storage id
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
  lib/Mount/MountProvider.php
Labels: backport-request, 3. to review

#1974 Fix MountProvider fetching paths on oracle
  lib/Mount/MountProvider.php
Labels: backport-request
