Repository nextcloud/groupfolders, pull requests merged in 2022-10, with the labels that each got.

#2114 return created groupfolder id from create command
  lib/Command/Create.php
Labels: backport-request, 3. to review

#2140 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2139 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2146 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2150 chore(ci): Update phpunit workflows
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
Labels: backport-request, 3. to review

#2147 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2154 Move check if node exists earlier
  lib/Trash/TrashBackend.php
Labels: bug, 3. to review
