Repository nextcloud/groupfolders, pull requests merged in 2023-12, with the labels that each got.

#2646 Update Psalm to 5.9 to sync with server
  composer.json
  composer.lock
  lib/Command/ListCommand.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/Listeners/CircleDestroyedEventListener.php
  lib/Listeners/LoadAdditionalScriptsListener.php
  lib/Mount/GroupFolderStorage.php
  lib/Versions/ExpireManager.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#2664 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2631 Fix ACL rules for trashed subfolders from groupfolders
  cypress/e2e/groupfolders.cy.ts
  cypress/e2e/groupfoldersUtils.ts
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  tests/ACL/ACLManagerTest.php
Labels: 3. to review

#2640 [stable28] Drop need of user folder
  lib/Versions/VersionsBackend.php
Labels: bug, 2. developing, php

#2679 Bump to v16.0.1
  appinfo/info.xml
Labels: 3. to review, release

#2677 Drop need of user folder
  lib/Versions/VersionsBackend.php
Labels: bug, 3. to review, php

#2687 v15.3.2
  appinfo/info.xml
Labels: 3. to review, release

#2660 fix(ACL): don't put inherited ACL permissions in the propPatch request payload
  src/components/SharingSidebarView.vue
Labels: bug, backport-request, 3. to review, javascript, feature: acl

#2691 chore(release): Bump version to 14.0.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#2641 Emit hook for restore
  lib/Trash/TrashBackend.php
Labels: 3. to review
