Repository nextcloud/groupfolders, pull requests merged in 2023-06, with the labels that each got.

#2407 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#2392 chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
Labels: 3. to review

#2413 fix PHP 8.2 ${var} deprecated
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/Scan.php
Labels: 3. to review

#2420 [stable26] `nextcloud/ocp` should be set to `dev-stable26`
  composer.json
  composer.lock
Labels: 3. to review

#2416 Fix readdir() call in loop with undesirable false evaluation potential
  lib/ACL/ACLStorageWrapper.php
Labels: 3. to review

#2423 Release 15
  .github/workflows/appstore-build-publish.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
  lib/Mount/GroupFolderStorage.php
  tests/stub.phpstub
Labels: 3. to review

#2435 Check if index exists before trying to delete it
  lib/Migration/Version1401000Date20230426112001.php
Labels: backport-request, 3. to review

#2447 Adapt to server API changes
  lib/Command/Scan.php
  lib/Helper/LazyFolder.php
  lib/Mount/GroupFolderStorage.php
  tests/stub.phpstub
Labels: bug, 3. to review
