Repository nextcloud/groupfolders, pull requests merged in 2023-08, with the labels that each got.

#2504 cleanup acl when deleting groups
  lib/ACL/ACLManager.php
  lib/Folder/FolderManager.php
Labels: 3. to review

#2507 [stable26] cleanup acl when deleting groups
  lib/ACL/ACLManager.php
  lib/Folder/FolderManager.php
Labels: backport-request, 3. to review

#2258 [25] cleanup trash from deleted groupfolders
  lib/Trash/TrashBackend.php
Labels: 3. to review

#2373 Translate User and Group strings
  src/settings/App.tsx
Labels: 3. to review

#2227 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2434 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2439 chore: update node engines to next LTS
  package.json
Labels: dependencies, 3. to review, automated

#2226 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2347 update folder used space after expiring items
  lib/Trash/TrashBackend.php
Labels: 3. to review

#2513 fix: Do not use `EventDispatcherInterface` but OCP `IEventDispatcher`
  composer.json
  lib/Versions/GroupVersionsExpireManager.php
  tests/stub.phpstub
Labels: 3. to review

#2512 Update php-cs workflow from organization and run `composer cs:fix`
  .github/workflows/lint-php-cs.yml
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupPlaceholder.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/Command/Scan.php
  lib/Controller/FolderController.php
  lib/DAV/PropFindPlugin.php
  lib/Folder/FolderManager.php
  lib/Migration/Version102020Date20180806161449.php
  lib/Migration/Version103000Date20180806161724.php
  lib/Migration/Version104000Date20180918132853.php
  lib/Migration/Version1401000Date20230426112002.php
  lib/Migration/Version201000Date20190111132839.php
  lib/Migration/Version201000Date20190212150323.php
  lib/Migration/Version401001Date20190715092137.php
  lib/Migration/Version501000Date20190927102434.php
  lib/Migration/Version501000Date20191218182434.php
  lib/Mount/MountProvider.php
  lib/Service/FoldersFilter.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/Trash/TrashBackend.php
  lib/Versions/VersionsBackend.php
  tests/ACL/ACLStorageWrapperTest.php
  tests/ACL/RuleManagerTest.php
Labels: 3. to review
