Repository nextcloud/groupfolders, pull requests merged in 2023-05, with the labels that each got.

#2341 Fix quota bar appearance
  src/settings/EditSelect.scss
Labels: backport-request, 3. to review

#2348 fix: Include `admin` group in list of all groups
  src/settings/Api.ts
Labels: bug, backport-request, 3. to review

#2355 UI improvements of the Group Folders' list
  src/settings/App.scss
Labels: 3. to review

#2354 feat: circles support to groupfolders
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Command/Group.php
  lib/Command/ListCommand.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/Controller/PageController.php
  lib/DAV/PropFindPlugin.php
  lib/Folder/FolderManager.php
  lib/Listeners/CircleDestroyedEventListener.php
  lib/Migration/Version1401000Date20230426112001.php
  lib/Migration/Version1401000Date20230426112002.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  src/settings/AdminGroupSelect.tsx
  src/settings/Api.ts
  src/settings/App.scss
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  templates/index.php
  tests/Folder/FolderManagerTest.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: enhancement, 4. to release

#2375 Check for folder existence in FolderController
  lib/Controller/FolderController.php
Labels: bug, help wanted, backport-request, 3. to review

#2380 trim slashes on hashed path
  lib/ACL/RuleManager.php
Labels: backport-request

#2387 Use the color-primary-element* variables
  src/components/SharingSidebarView.vue
  src/settings/FolderGroups.tsx
Labels: bug, 3. to review, design

#2400 15.0.0-beta2
  appinfo/info.xml
Labels: 3. to review

#2389 (docs) README - Minor typos, clarifications, and organizational refinements
  README.md
Labels: 3. to review
