Repository nextcloud/groupfolders, pull requests merged in 2023-07, with the labels that each got.

#2457 fix: fix open groupfolder in files
  src/actions/openGroupfolderAction.ts
Labels: bug, backport-request, 3. to review

#2453 preload the acl rules for the root of the groupfolders
  lib/Mount/MountProvider.php
Labels: 3. to review

#2377 [stable25] Check for folder existence in FolderController
  lib/Controller/FolderController.php
Labels: bug, help wanted

#2476 Check if $user is set before calling it
  lib/Mount/MountProvider.php
Labels: bug, backport-request, regression
