Repository nextcloud/groupfolders, pull requests merged in 2023-11, with the labels that each got.

#2607 remove custom lazyfolder implementation + 16.0.0
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Helper/LazyFolder.php
  tests/stub.phpstub
Labels: 3. to review

#2634 Rename param names as defined by OCP\Files\Storage\IStorage
  lib/ACL/ACLStorageWrapper.php
Labels: 3. to review

#2546 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2645 Use new API to register Files view
  src/main.ts
Labels: bug, backport-request, 2. developing, javascript

#2649 [stable28] build(deps): Bump @nextcloud/files from 3.0.0-beta.11 to 3.0.0
  .eslintrc.js
  package-lock.json
  package.json
  src/actions/openGroupfolderAction.ts
  src/components/AclStateButton.vue
  src/services/groupfolders.ts
  src/settings/AdminGroupSelect.tsx
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/SubAdminGroupSelect.tsx
  src/settings/SubmitInput.tsx
  src/settings/index.tsx
Labels: dependencies, 3. to review, javascript

#2643 Add cypress config
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/.eslintrc.js
  cypress/docker-compose.yml
  cypress/dockerNode.ts
  cypress/e2e/groupfolders.cy.ts
  cypress/e2e/groupfoldersUtils.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  cypress/utils/index.js
  package-lock.json
  package.json
  tsconfig.json
Labels: 3. to review, tests
