Repository nextcloud/groupfolders, pull requests merged in 2023-02, with the labels that each got.

#2245 cleanup trash from deleted groupfolders
  lib/Trash/TrashBackend.php
Labels: 3. to review

#2262 fix: Adapt return type for Nextcloud 26
  composer.lock
  lib/ACL/ACLManager.php
  lib/ACL/ACLStorageWrapper.php
  lib/Controller/FolderController.php
  lib/Versions/GroupVersion.php
Labels: bug, 3. to review

#2268 fix(sidebar): Use icon slot for read-only ACL states
  src/components/AclStateButton.vue
Labels: bug, 3. to review

#2271 fix(a11y): Add title and label to read-only ACL buttons
  src/components/AclStateButton.vue
Labels: bug, backport-request, 3. to review

#2277 bumb version to 14.0.0
  appinfo/info.xml
Labels: 3. to review
