Repository nextcloud/groupfolders, pull requests merged in 2023-01, with the labels that each got.

#2219 Log instead of throw for trash item not removable
  lib/AppInfo/Application.php
  lib/Trash/TrashBackend.php
Labels: 3. to review

#2222 [stable25] update to vue 7.3.0
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#2204 Fix usability of settings components using dark color theme
  img/rename.svg
  src/settings/App.scss
  src/settings/App.tsx
  src/settings/EditSelect.scss
  src/settings/FolderGroups.scss
  src/settings/FolderGroups.tsx
Labels: 3. to review, ui
