Repository nextcloud/groupfolders, pull requests merged in 2023-09, with the labels that each got.

#2538 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2539 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2543 Adapt version backend to new features
  lib/AppInfo/Application.php
  lib/Helper/LazyFolder.php
  lib/Migration/Version16000Date20230821085801.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionEntity.php
  lib/Versions/GroupVersionsMapper.php
  lib/Versions/VersionsBackend.php
  tests/stub.phpstub
Labels: bug, enhancement, backport-request, 3. to review, php, feature: versions

#2549 [stable27] Revert: Adapt version backend to new features
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Helper/LazyFolder.php
  lib/Migration/Version16000Date20230821085801.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionEntity.php
  lib/Versions/GroupVersionsMapper.php
  lib/Versions/VersionsBackend.php
  tests/stub.phpstub
Labels: bug, 3. to review

#2550 [stable27] Reapply: Adapt version backend to new features
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Helper/LazyFolder.php
  lib/Migration/Version16000Date20230821085801.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionEntity.php
  lib/Versions/GroupVersionsMapper.php
  lib/Versions/VersionsBackend.php
  tests/stub.phpstub
Labels: enhancement, 3. to review

#2560 pass around preload rules in acl wrapper instead of relying on the cache
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/Rule.php
  lib/Listeners/CircleDestroyedEventListener.php
  lib/Migration/Version1401000Date20230426112001.php
  lib/Migration/Version16000Date20230821085801.php
  lib/Mount/MountProvider.php
  lib/Settings/Admin.php
  lib/Versions/GroupVersion.php
Labels: backport-request, 3. to review

#2562 [26] pass around preload rules in acl wrapper instead of relying on the cache
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/Rule.php
  lib/Mount/MountProvider.php
Labels: 3. to review

#2563 [25] pass around preload rules in acl wrapper instead of relying on the cache
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/Rule.php
  lib/Mount/MountProvider.php
Labels: 3. to review

#2569 13.1.6
  appinfo/info.xml
Labels: 3. to review

#2568 14.0.5
  appinfo/info.xml
Labels: 3. to review

#2570 fix incorrect stat headers when scanning groupfolders
  lib/Command/Scan.php
Labels: 3. to review
