Repository nextcloud/groupfolders, pull requests merged in 2024-11, with the labels that each got.

#3386 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3369 refactor: Use constructor property promotion where possible
  lib/ACL/ACLStorageWrapper.php
  lib/Mount/GroupFolderStorage.php
  lib/Mount/RootPermissionsMask.php
  lib/Trash/GroupTrashItem.php
  rector.php
  tests/Folder/FolderManagerTest.php
Labels: 3. to review, technical debt

#3399 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3406 test: Fix cypress tests
  cypress.config.ts
  cypress/e2e/encryption.cy.ts
  cypress/e2e/files/filesUtils.ts
  cypress/e2e/files_versions/version_cross_storage_move.cy.ts
  cypress/e2e/groupfolders.cy.ts
  cypress/e2e/groupfoldersUtils.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, 3. to review

#3407 fix(routes): Revert back to index.php routes
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  src/components/SharingSidebarView.vue
  src/settings/Api.ts
Labels: 3. to review

#3324 feat: Add OpenAPI
  .eslintrc.js
  .github/workflows/openapi.yml
  README.md
  REUSE.toml
  composer.json
  lib/AppInfo/Capabilities.php
  lib/Command/FolderCommand.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/DAV/GroupFoldersHome.php
  lib/Folder/FolderManager.php
  lib/Mount/MountProvider.php
  lib/ResponseDefinitions.php
  lib/Service/FoldersFilter.php
  lib/Trash/TrashBackend.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  openapi.json
  package-lock.json
  package.json
  src/settings/AdminGroupSelect.tsx
  src/settings/Api.ts
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/SubAdminGroupSelect.tsx
  src/types/index.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: enhancement, 3. to review

#3411 build: Exclude vendor-bin from PHP lint
  composer.json
Labels: bug, 3. to review

#3410 [stable30] feat: Add OpenAPI
  .eslintrc.js
  .github/workflows/openapi.yml
  README.md
  REUSE.toml
  composer.json
  composer.lock
  lib/AppInfo/Capabilities.php
  lib/Command/FolderCommand.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/DAV/GroupFoldersHome.php
  lib/Folder/FolderManager.php
  lib/Mount/MountProvider.php
  lib/ResponseDefinitions.php
  lib/Service/FoldersFilter.php
  lib/Trash/TrashBackend.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  openapi.json
  package-lock.json
  package.json
  src/settings/AdminGroupSelect.tsx
  src/settings/Api.ts
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/SubAdminGroupSelect.tsx
  src/types/index.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review

#3412 build: Bump version
  appinfo/info.xml
Labels: 3. to review

#3417 fix(deps): Update openapi-extractor to v1.2.2
  openapi.json
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.lock
Labels: backport-request

#3393 Fix labeled version autoExpire
  lib/Versions/ExpireManager.php
Labels: bug, backport-request, 3. to review, php, feature: versions

#3431 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3387 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3432 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3404 fix: implement 'per user inherit' logic for folder delete permissions check
  lib/ACL/ACLManager.php
  lib/ACL/Rule.php
  lib/ACL/RuleManager.php
  tests/ACL/ACLManagerTest.php
Labels: backport-request, 3. to review

#3433 ignore inShare from cli
  lib/Mount/MountProvider.php
Labels: 3. to review

#3444 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3443 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3442 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3401 feat(GroupMountPoint): Implement IShareOwnerlessMount
  composer.lock
  lib/Mount/GroupMountPoint.php
Labels: enhancement, 3. to review
