Repository nextcloud/groupfolders, pull requests merged in 2024-01, with the labels that each got.

#2695 [stable28] Update Psalm to 5.9 to sync with server
  composer.json
  composer.lock
  lib/ACL/ACLStorageWrapper.php
  lib/Command/ListCommand.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/Listeners/CircleDestroyedEventListener.php
  lib/Listeners/LoadAdditionalScriptsListener.php
  lib/Mount/GroupFolderStorage.php
  lib/Versions/ExpireManager.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review

#2684 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2644 Add a listener to update trashed items when parent is renamed
  cypress/e2e/groupfolders.cy.ts
  lib/AppInfo/Application.php
  lib/Listeners/NodeRenamedListener.php
  lib/Trash/TrashManager.php
Labels: backport-request, 3. to review

#2658 Update README: Add server-side encryption command
  README.md
Labels: 3. to review, documentation, feature: encryption, feedback-requested

#2712 [stable28] Add a listener to update trashed items when parent is renamed
  lib/AppInfo/Application.php
  lib/Listeners/NodeRenamedListener.php
  lib/Trash/TrashManager.php
Labels: 3. to review

#2642 don't apply acls when scanning
  lib/Mount/GroupFolderStorage.php
  tests/stub.phpstub
Labels: 3. to review

#2714 fix downloading trashbin items
  lib/Trash/GroupTrashItem.php
Labels: 4. to release

#2726 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2725 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2731 [stable27] don't apply acls when scanning
  lib/Mount/GroupFolderStorage.php
Labels: backport-request, 3. to review

#2713 [stable27] Add a listener to update trashed items when parent is renamed
  lib/AppInfo/Application.php
  lib/Listeners/NodeRenamedListener.php
  lib/Trash/TrashManager.php
  tests/psalm-baseline.xml
Labels: 3. to review

#2744 [stable26] Add a listener to update trashed items when parent is renamed
  lib/AppInfo/Application.php
  lib/Listeners/NodeRenamedListener.php
  lib/Trash/TrashManager.php
  tests/psalm-baseline.xml
Labels: 3. to review

#2746 [28] restore acl ui in sharing tab
  package-lock.json
  package.json
  src/SharingSidebarApp.js
  src/client.js
  src/components/AclStateButton.vue
  src/components/SharingSidebarView.vue
  src/files.js
Labels: 3. to review

#2758 Handle missing disk versions
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
Labels: bug, backport-request, 3. to review, php

#2752 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2751 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2760 Bump to v16.0.3
  appinfo/info.xml
Labels: 3. to review, release

#2763 [stable27] Handle missing disk versions
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
Labels: bug, 3. to review

#2765 v15.3.4
  appinfo/info.xml
Labels: 3. to review, release

#2775 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2787 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2728 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2777 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2767 Command/Rename: add type declarations
  lib/Command/Rename.php
Labels: 3. to review, technical debt
