Repository nextcloud/groupfolders, pull requests merged in 2024-07, with the labels that each got.

#2813 don't error if we can't find a trashbin item for a file when looking …
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
Labels: 3. to review

#3015 fix(DavClient): Provide proper feedback for dav requests
  package-lock.json
  package.json
  src/client.js
  src/components/SharingSidebarView.vue
  src/services/logger.ts
Labels: 3. to review, feature: acl

#3044 fix: files versions cypress test
  cypress/e2e/files_versions/filesVersionsUtils.ts
Labels: 3. to review

#3043 fix: ACLManager tests
  tests/ACL/ACLManagerTest.php
Labels: 3. to review

#3042 fix: check if array key exists
  lib/Controller/FolderController.php
Labels: 3. to review

#3045 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3054 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3012 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3030 feat: spread group folder expiry background job
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/Versions/GroupVersionsExpireManager.php
Labels: enhancement, 3. to review

#3047 fix: Rename Circle to Team
  lib/Command/Group.php
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
Labels: backport-request

#3071 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3072 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3050 fix(AclStateButton): Increase contrast for inherited permissions
  src/components/AclStateButton.vue
Labels: enhancement, 3. to review

#3013 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3004 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2981 Sync npm version with server
  package.json
Labels: 3. to review

#2807 chore: Add cypress test for deletion from trashbin
  cypress/e2e/groupfolders.cy.ts
  cypress/e2e/groupfoldersUtils.ts
Labels: 2. developing

#3075 fix: Adjust type definitions for global Nextcloud variables
  package-lock.json
  package.json
  src/custom.d.ts
  src/globals.d.ts
  src/main.ts
  src/settings/AdminGroupSelect.tsx
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/Nextcloud.d.ts
  src/settings/QuotaSelect.tsx
  src/settings/SubAdminGroupSelect.tsx
  src/settings/index.tsx
  tsconfig.json
Labels: 3. to review

#3063 fix: improve handling of ACL rules in trashbin
  lib/ACL/ACLManager.php
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3076 More acl trashbin fixes
  lib/Trash/TrashBackend.php
  tests/Trash/TrashBackendTest.php
Labels: 3. to review

#3048 ci: upgrade cypress action dependency
  .github/workflows/cypress.yml
Labels: 3. to review

#3081 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
