Repository nextcloud/groupfolders, pull requests merged in 2024-03, with the labels that each got.

#2856 fix: fix fully inherited acl state not being show as inherited
  src/components/AclStateButton.vue
Labels: 3. to review

#2859 v17.0.0-beta.1
  appinfo/info.xml
Labels: 3. to review, release

#2826 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2857 chore(files_versions): Use new metadata API for versions
  cypress/e2e/files/filesUtils.ts
  cypress/e2e/files_versions/filesVersionsUtils.ts
  cypress/e2e/files_versions/version_creation.cy.ts
  cypress/e2e/files_versions/version_deletion.cy.ts
  cypress/e2e/files_versions/version_download.cy.ts
  cypress/e2e/files_versions/version_naming.cy.ts
  cypress/e2e/files_versions/version_restoration.cy.ts
  cypress/e2e/groupfoldersUtils.ts
  lib/AppInfo/Application.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionEntity.php
  lib/Versions/VersionsBackend.php
  tests/stub.phpstub
Labels: 3. to review, technical debt, php, feature: versions

#2870 feat: add option to resolve inherited option per-user instead of per-path
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/ACL/Rule.php
  lib/AppInfo/Application.php
  tests/ACL/ACLManagerTest.php
Labels: 3. to review, php, feature: acl, documentation

#2883 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2898 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
