Repository nextcloud/groupfolders, pull requests merged in 2024-08, with the labels that each got.

#3089 fix: fix access to version trough shares
  lib/Versions/VersionsBackend.php
Labels: 3. to review

#3083 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3098 fix: folder icon
  img/app-dark.svg
  img/app.svg
  package-lock.json
  package.json
  src/main.ts
Labels: bug, 3. to review, design

#2936 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3107 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3109 Update info.xml
  appinfo/info.xml
Labels: 3. to review

#3096 emit audit log events for changes to groupfolders
  lib/ACL/Rule.php
  lib/Command/ACL.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/Folder/FolderManager.php
  tests/Folder/FolderManagerTest.php
Labels: backport-request, 3. to review

#3119 16.0.8
  appinfo/info.xml
Labels: 3. to review

#3117 18.0.0
  appinfo/info.xml
Labels: 3. to review

#3118 17.0.2
  appinfo/info.xml
Labels: 3. to review

#2942 Fix encryption wrapper not seen by groupfolder cache
  cypress/e2e/encryption.cy.ts
  cypress/e2e/files/filesUtils.ts
  cypress/e2e/groupfoldersUtils.ts
  lib/Mount/GroupFolderEncryptionJail.php
  lib/Mount/MountProvider.php
  tests/stub.phpstub
Labels: bug, backport-request, 3. to review

#3094 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3122 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3014 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3053 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#3137 [stable29] fix: load script on init step
  lib/Listeners/LoadAdditionalScriptsListener.php
  src/actions/openGroupfolderAction.ts
  src/init.ts
  webpack.js
Labels: bug, 3. to review

#3143 fix(cypress): cypress branch env
  .github/workflows/cypress.yml
  cypress.config.ts
Labels: bug, 4. to release, regression

#2861 Expose the app version to the capabilities endpoint
  lib/AppInfo/Capabilities.php
Labels: 4. to release, feature: api, feedback-requested

#3108 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 4. to release

#2925 Move CappedMemoryCache to OCP
  lib/ACL/ACLManager.php
Labels: 4. to release

#2232 Shallow scanning of specific paths
  lib/Command/Scan.php
Labels: 3. to review, feature: occ
