Repository nextcloud/groupfolders, pull requests merged in 2024-05, with the labels that each got.

#2867 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2937 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2872 fix: Set mount point target user as storage owner
  lib/Mount/MountProvider.php
Labels: 3. to review

#2959 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2957 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2949 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2958 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2951 fix: Adapt to constructor change of TrashItem in files_trashbin
  lib/Trash/GroupTrashItem.php
  tests/stub.phpstub
Labels: bug, 3. to review, feature: trashbin

#2962 17.0.0
  appinfo/info.xml
Labels: 3. to review

#2963 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2969 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2970 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2974 Fix translation group
  src/main.ts
Labels: backport-request, 3. to review
