Repository nextcloud/groupfolders, pull requests merged in 2024-09, with the labels that each got.

#3154 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3158 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3157 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3160 feat(settings): Make default quota configurable
  README.md
  appinfo/info.xml
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/Migration/Version102020Date20180806161449.php
  lib/Migration/Version19000Date20240903062631.php
  src/settings/Api.ts
  src/settings/App.tsx
  tests/Folder/FolderManagerTest.php
Labels: backport-request, 3. to review, feature: quota

#3164 chore: Prepare v17.0.3
  appinfo/info.xml
Labels: 3. to review, release

#3163 chore: Prepare v18.0.1
  appinfo/info.xml
Labels: 3. to review, release

#3161 fix(settings): Calculate correct default quota option sizes
  appinfo/info.xml
  lib/Migration/WrongDefaultQuotaRepairStep.php
  src/settings/App.tsx
Labels: bug, backport-request, 4. to release

#3165 chore: Prepare v16.0.9
  .github/workflows/lint-eslint.yml
  appinfo/info.xml
Labels: 3. to review, release

#3155 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3183 fix(versions): Handle missing versions folder
  lib/Versions/VersionsBackend.php
Labels: bug, backport-request, 3. to review

#3184 feat(psalm): Enable more/less specific issue handlers
  lib/Folder/FolderManager.php
  lib/Trash/TrashBackend.php
  lib/Versions/VersionsBackend.php
  psalm.xml
Labels: enhancement, 3. to review

#3170 feat: Save deleted by property
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Migration/Version300000Date20240905185515.php
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  tests/Trash/TrashBackendTest.php
Labels: enhancement, backport-request, 3. to review, php, feature: trashbin

#3188 chore(deps): Update nextcloud/coding-standard to v1.2.3
  composer.lock
  lib/AppInfo/Application.php
  lib/Command/ListCommand.php
  lib/Command/Scan.php
  lib/Controller/DelegationController.php
  lib/DAV/GroupFoldersHome.php
  lib/Folder/FolderManager.php
  lib/Migration/Version16000Date20230821085801.php
  lib/Mount/MountProvider.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/Trash/TrashBackend.php
  lib/Versions/GroupVersionsMapper.php
  lib/Versions/VersionsBackend.php
  tests/Trash/TrashBackendTest.php
Labels: 3. to review, dependencies: php

#3192 fix(ACL): Actually return in ACLStorageWrapper methods
  lib/ACL/ACLStorageWrapper.php
  tests/psalm-baseline.xml
Labels: bug, backport-request, 3. to review

#3159 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3179 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3178 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3196 chore(psalm): Remove dead logic
  lib/Versions/ExpireManager.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#3191 fix 3130 : missing translations for Transifex
  src/settings/App.tsx
Labels: backport-request

#3200 refactor(settings): Use Promise for API requests
  package-lock.json
  package.json
  src/settings/Api.ts
Labels: 3. to review

#3201 refactor(settings): Remove usage of jQuery
  src/settings/Api.ts
  src/settings/Nextcloud.d.ts
Labels: 3. to review, technical debt

#3204 refactor: Replace \OC::$server->get with \OCP\Server::get
  lib/Command/Trashbin/Cleanup.php
  lib/Folder/FolderManager.php
  lib/Mount/MountProvider.php
  tests/Trash/TrashBackendTest.php
Labels: 3. to review

#3156 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3207 fix(eslint): Also check .ts and .tsx files
  package.json
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/Nextcloud.d.ts
  src/settings/QuotaSelect.tsx
  src/settings/SortArrow.tsx
  src/settings/SubmitInput.tsx
  src/settings/index.tsx
Labels: bug, 3. to review

#3219 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3220 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3213 fix: Do not expire labeled versions
  cypress.config.ts
  cypress/e2e/files_versions/filesVersionsUtils.ts
  cypress/e2e/files_versions/version_creation.cy.ts
  cypress/e2e/files_versions/version_deletion.cy.ts
  cypress/e2e/files_versions/version_download.cy.ts
  cypress/e2e/files_versions/version_expiration.cy.ts
  cypress/e2e/files_versions/version_naming.cy.ts
  cypress/e2e/files_versions/version_restoration.cy.ts
  cypress/support/commands.ts
  lib/Versions/ExpireManager.php
Labels: bug, backport-request, 3. to review, php, feature: versions

#3222 chore(CI): Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: dependencies

#2768 Update Command/ExpireGroupBase: add type declarations
  lib/Command/ExpireGroup/ExpireGroupBase.php
  lib/Command/ExpireGroup/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
Labels: 2. developing, technical debt, feedback-requested

#3227 perf(psalm): Use multiple threads
  composer.json
Labels: performance :rocket:

#3228 feat(security): Add roave/security-advisories
  composer.json
  composer.lock
Labels: enhancement, dependencies: php

#3230 fix(psalm): Disable broken cache
  composer.json
Labels: bug

#3229 chore(deps): Remove unused dependencies
  composer.json
Labels: 3. to review, dependencies: php

#3221 [stable28] Fix npm audit
  package-lock.json
  src/settings/AdminGroupSelect.tsx
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/SubAdminGroupSelect.tsx
  src/settings/index.tsx
Labels: dependencies, 3. to review

#3177 [stable28] Update nextcloud/ocp dependency
  composer.lock
  tests/stub.phpstub
Labels: dependencies, 3. to review

#3232 refactor(FolderManager): Simplify CirclesManager access
  lib/Folder/FolderManager.php
Labels: 3. to review

#3233 refactor: Change some returns from false to null
  lib/ACL/ACLCacheWrapper.php
  lib/Command/ACL.php
  lib/Command/Delete.php
  lib/Command/FolderCommand.php
  lib/Command/Group.php
  lib/Command/Quota.php
  lib/Command/Rename.php
  lib/Command/Scan.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
Labels: 3. to review, technical debt

#3231 chore(deps): Move cs-fixer, phpunit and psalm to vendor-bin
  .github/dependabot.yml
  .php-cs-fixer.dist.php
  REUSE.toml
  composer.json
  composer.lock
  psalm.xml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies: php

#3237 feat(phpunit): Enable phpunit to collect coverage reports and save them as HTML
  .gitignore
  composer.json
  tests/phpunit.xml
Labels: enhancement, 3. to review

#3238 fix(CacheListener): Use OCP IEventDispatcher
  composer.json
  composer.lock
  lib/CacheListener.php
  lib/Mount/GroupFolderStorage.php
Labels: backport-request, 3. to review, dependencies: php, technical debt

#3244 refactor: Change callback notation to be more readable
  lib/ACL/ACLCacheWrapper.php
  lib/CacheListener.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/DAV/GroupFoldersHome.php
  lib/DAV/PropFindPlugin.php
Labels: 3. to review

#3243 fix(psalm): Fix @throws annotations
  lib/Trash/TrashBackend.php
Labels: 3. to review, technical debt

#3249 chore(deps): Update nextcloud/coding-standard to v1.3.0
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/Rule.php
  lib/ACL/RuleManager.php
  lib/AppInfo/Application.php
  lib/AppInfo/Capabilities.php
  lib/AuthorizedAdminSettingMiddleware.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/CacheListener.php
  lib/Command/ACL.php
  lib/Command/Create.php
  lib/Command/Delete.php
  lib/Command/ExpireGroup/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
  lib/Command/FolderCommand.php
  lib/Command/Group.php
  lib/Command/ListCommand.php
  lib/Command/Quota.php
  lib/Command/Rename.php
  lib/Command/Scan.php
  lib/Command/Trashbin/Cleanup.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/DAV/GroupFoldersHome.php
  lib/DAV/RootCollection.php
  lib/Folder/FolderManager.php
  lib/Listeners/NodeRenamedListener.php
  lib/Migration/Version1000000Date20210216085047.php
  lib/Migration/Version102020Date20180806161449.php
  lib/Mount/CacheRootPermissionsMask.php
  lib/Mount/GroupFolderEncryptionJail.php
  lib/Mount/GroupFolderStorage.php
  lib/Mount/MountProvider.php
  lib/Mount/RootEntryCache.php
  lib/Mount/RootPermissionsMask.php
  lib/Service/DelegationService.php
  lib/Service/FoldersFilter.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  lib/Versions/ExpireManager.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  tests/ACL/ACLManagerTest.php
  tests/ACL/ACLScannerTest.php
  tests/ACL/RuleManagerTest.php
  tests/Folder/FolderManagerTest.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review

#3248 build: Add rector
  composer.json
  lib/AppInfo/Application.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/Scan.php
  rector.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: 3. to review

#3250 Remove all usage of deprecated code
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
  lib/Attribute/RequireGroupFolderAdmin.php
  lib/AuthorizedAdminSettingMiddleware.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/CacheListener.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
  lib/Command/Trashbin/Cleanup.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/Event/GroupVersionsExpireDeleteFileEvent.php
  lib/Event/GroupVersionsExpireDeleteVersionEvent.php
  lib/Event/GroupVersionsExpireEnterFolderEvent.php
  lib/Migration/Version19000Date20240903062631.php
  lib/Migration/Version501000Date20190927102434.php
  lib/Versions/GroupVersionsExpireManager.php
  psalm.xml
Labels: backport-request, 3. to review, technical debt

#3256 [stable28] refactor(Application): Migrate to typed GroupDeletedEvent event
  lib/AppInfo/Application.php
Labels: 3. to review

#3252 Refactor with rector
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/Rule.php
  lib/ACL/RuleManager.php
  lib/ACL/UserMapping/UserMappingManager.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/Command/ACL.php
  lib/Command/ListCommand.php
  lib/Command/Scan.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/DAV/PropFindPlugin.php
  lib/Folder/FolderManager.php
  lib/Listeners/NodeRenamedListener.php
  lib/Mount/CacheRootPermissionsMask.php
  lib/Mount/MountProvider.php
  lib/Mount/RootPermissionsMask.php
  lib/Service/FoldersFilter.php
  lib/Trash/TrashBackend.php
  lib/Versions/ExpireManager.php
  lib/Versions/VersionsBackend.php
  rector.php
  tests/ACL/ACLCacheWrapperTest.php
  tests/ACL/ACLManagerTest.php
  tests/ACL/ACLScannerTest.php
  tests/ACL/ACLStorageWrapperTest.php
  tests/ACL/RuleManagerTest.php
  tests/ACL/RuleTest.php
  tests/Folder/FolderManagerTest.php
  tests/Trash/TrashBackendTest.php
Labels: 3. to review, technical debt

#3253 test: Fix all types
  psalm.xml
  tests/ACL/ACLCacheWrapperTest.php
  tests/ACL/ACLManagerTest.php
  tests/ACL/ACLScannerTest.php
  tests/ACL/ACLStorageWrapperTest.php
  tests/ACL/RuleManagerTest.php
  tests/ACL/RuleTest.php
  tests/Folder/FolderManagerTest.php
  tests/stubs/oc_files_setupmanager.php
  tests/stubs/oc_files_storage_local.php
  tests/stubs/oc_files_storage_temporary.php
  tests/stubs/oc_group_database.php
  tests/stubs/oc_server.php
  tests/stubs/test_testcase.php
  tests/stubs/test_traits_usertrait.php
Labels: 3. to review, technical debt

#3257 fix: Add missing null checks
  lib/Command/FolderCommand.php
  lib/Command/ListCommand.php
  lib/Command/Trashbin/Cleanup.php
  lib/Controller/DelegationController.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/DAV/GroupFoldersHome.php
  lib/DAV/PropFindPlugin.php
  lib/Folder/FolderManager.php
  lib/Mount/GroupMountPoint.php
  lib/Service/DelegationService.php
  lib/Service/FoldersFilter.php
  psalm.xml
Labels: 3. to review

#3258 fix(psalm): Enable psalm level 3
  lib/ACL/ACLManager.php
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/UserMapping/UserMappingManager.php
  lib/DAV/ACLPlugin.php
  lib/Folder/FolderManager.php
  lib/Mount/GroupMountPoint.php
  lib/Mount/MountProvider.php
  psalm.xml
Labels: 3. to review

#3259 fix(psalm): Fix falsable return for getOwner()
  composer.lock
  lib/Mount/GroupFolderStorage.php
Labels: 3. to review

#3260 test: Add tests for Capabilities
  tests/AppInfo/CapabilitiesTest.php
Labels: 3. to review, tests

#3261 test: Add tests for Events
  tests/Event/GroupVersionsExpireDeleteFileEventTest.php
  tests/Event/GroupVersionsExpireDeleteVersionEventTest.php
  tests/Event/GroupVersionsExpireEnterFolderEventTest.php
Labels: 3. to review

#3271 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3272 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3273 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3274 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3280 fix(ACLStorageWrapper): Fix return types
  lib/ACL/ACLStorageWrapper.php
  psalm.xml
  tests/ACL/ACLScannerTest.php
  tests/stubs/oc_files_cache_cache.php
  tests/stubs/oc_files_objectstore_objectstorestorage.php
  tests/stubs/oc_files_setupmanager.php
  tests/stubs/oc_files_storage_common.php
  tests/stubs/oc_files_storage_local.php
  tests/stubs/oc_files_storage_storage.php
  tests/stubs/oc_files_storage_temporary.php
  tests/stubs/oc_files_storage_wrapper_jail.php
  tests/stubs/oc_files_storage_wrapper_permissionsmask.php
  tests/stubs/oc_files_storage_wrapper_quota.php
  tests/stubs/oc_files_storage_wrapper_wrapper.php
  tests/stubs/oc_server.php
  tests/stubs/ocp_files_storage_iconstructablestorage.php
  tests/stubs/test_testcase.php
Labels: 3. to review, technical debt

#3294 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3296 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3295 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3293 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/ACL/ACLStorageWrapper.php
  lib/Mount/GroupFolderStorage.php
Labels: dependencies, 3. to review
