Repository nextcloud/groupfolders, pull requests merged in 2024-04, with the labels that each got.

#2900 properly distinguish between inherited and unset permissions
  cypress/e2e/groupfoldersUtils.ts
  lib/DAV/ACLPlugin.php
  src/client.js
  src/components/AclStateButton.vue
  src/components/SharingSidebarView.vue
  src/model/Rule.js
Labels: 3. to review

#2860 Support moving versions across storages
  .gitignore
  cypress.config.ts
  cypress/e2e/files/filesUtils.ts
  cypress/e2e/files_versions/filesVersionsUtils.ts
  cypress/e2e/files_versions/version_cross_storage_move.cy.ts
  cypress/e2e/files_versions/version_download.cy.ts
  cypress/e2e/files_versions/version_restoration.cy.ts
  cypress/support/e2e.ts
  lib/Versions/VersionsBackend.php
  tests/stub.phpstub
Labels: enhancement, 2. developing, php, feature: versions

#2914 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2852 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2853 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2847 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#2916 fix: fix opening acl create select
  src/components/SharingSidebarView.vue
Labels: backport-request, 3. to review

#2923 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2922 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2869 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2868 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2930 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2939 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
