Repository nextcloud/groupfolders, pull requests merged in 2024-06, with the labels that each got.

#2984 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2986 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2983 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2989 fix: Typing of new getVersionsForFile method
  lib/Versions/VersionsBackend.php
Labels: bug, backport-request, 4. to release, php

#2991 Trim whitespace from mountpoint names
  lib/Controller/FolderController.php
Labels: bug, backport-request, 3. to review, php

#2985 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3007 Update icons to Material Symbol
  img/app-dark.svg
  img/app.svg
  img/deny.svg
  img/folder-group.svg
Labels: 3. to review, design

#3006 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3022 [stable27] fix: Get Proper Node object when creating GroupVersion
  lib/Versions/VersionsBackend.php
Labels: bug, 3. to review

#3026 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3027 fix: Adjust sidebar data attribute name to changes in server
  cypress/e2e/files/filesUtils.ts
Labels: bug, 3. to review, tests

#3025 Update dependencies to switch to node v20
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, tests

#3036 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3037 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
