Repository nextcloud/groupfolders, pull requests merged in 2024-12, with the labels that each got.

#3454 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3452 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3453 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3455 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3457 [stable30] fix(QuotaSelect): Fix quota usage tooltip
  src/settings/QuotaSelect.tsx
Labels: bug, 3. to review

#3459 [stable28] fix(QuotaSelect): Fix quota usage tooltip
  src/settings/QuotaSelect.tsx
Labels: bug, 3. to review

#3460 fix(settings): Fix select input color
  src/settings/AdminGroupSelect.tsx
  src/settings/App.tsx
  src/settings/FolderGroups.tsx
  src/settings/SubAdminGroupSelect.tsx
Labels: bug, backport-request, 3. to review

#3475 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3483 fix: hint table for columns where needed for sharded queries
  lib/ACL/RuleManager.php
  lib/Folder/FolderManager.php
Labels: 3. to review

#3486 18.0.8
  appinfo/info.xml
Labels: 3. to review

#3485 17.0.8
  appinfo/info.xml
Labels: 3. to review

#3492 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3491 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3493 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3503 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3502 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3501 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3510 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
