Repository nextcloud/groupfolders, pull requests merged in 2024-02, with the labels that each got.

#2804 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2803 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#2766 ExpireGroupVersionsTrash: add type declarations
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
Labels: 3. to review, technical debt, feedback-requested

#2806 fix(ci): Wait for preview to load to avoid 423 errors when deleting file
  cypress/e2e/groupfolders.cy.ts
  cypress/e2e/groupfoldersUtils.ts
Labels: 3. to review

#2797 Revert: don't apply acls when scanning
  lib/Mount/GroupFolderStorage.php
  tests/ACL/ACLScannerTest.php
Labels: 3. to review

#2809 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#2727 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#2817 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
