Repository nextcloud/groupfolders, pull requests merged in 2024-10, with the labels that each got.

#3262 test: Add tests for Listeners
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  lib/Listeners/LoadAdditionalScriptsListener.php
  lib/Listeners/NodeRenamedListener.php
  tests/Listeners/CircleDestroyedEventListenerTest.php
  tests/Listeners/LoadAdditionalScriptsListenerTest.php
  tests/Listeners/NodeRenamedListenerTest.php
  tests/bootstrap.php
Labels: 3. to review

#3307 fix(ACLPlugin): Fix PROPFIND acl-list when rules are empty
  lib/DAV/ACLPlugin.php
Labels: bug, 3. to review

#3308 fix(eslint): Remove JQuery Thenable
  src/settings/App.tsx
Labels: 3. to review, technical debt

#3311 fix(ACLStorageWrapper): Fix getDirectoryContent() return type
  lib/ACL/ACLStorageWrapper.php
  tests/stubs/oc_files_node_lazyfolder.php
  tests/stubs/oc_files_objectstore_objectstorestorage.php
  tests/stubs/oc_files_storage_common.php
  tests/stubs/oc_files_storage_storage.php
  tests/stubs/oc_files_storage_wrapper_jail.php
  tests/stubs/oc_files_storage_wrapper_wrapper.php
Labels: bug, 3. to review

#3318 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3322 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3321 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3320 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3316 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3317 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3319 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3325 fix(FolderManager): Use placeholder value for default quota instead of the current value on creation
  lib/Folder/FolderManager.php
  src/settings/App.tsx
  tests/Folder/FolderManagerTest.php
Labels: bug, backport-request, 3. to review

#3331 [stable28] fix: improve handling of ACL rules in trashbin
  lib/ACL/ACLManager.php
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3330 [stable29] fix: improve handling of ACL rules in trashbin
  lib/ACL/ACLManager.php
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3328 fix: Override check for applying quota in wrapper
  lib/Mount/GroupFolderStorage.php
Labels: bug, backport-request, 3. to review, feature: quota

#3326 fix: update parent etag when changing acl rules
  lib/DAV/ACLPlugin.php
Labels: 3. to review

#3351 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3349 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3348 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3350 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3332 [stable27] fix: improve handling of ACL rules in trashbin
  lib/ACL/ACLManager.php
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3362 fix: include mountpoint in original location for trash items
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
Labels: backport-request, 3. to review

#3374 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3373 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3383 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3384 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
