Repository nextcloud/groupfolders, pull requests merged in 2025-04, with the labels that each got.

#3729 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3732 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3731 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3728 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3719 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3742 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3741 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3624 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3748 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3730 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3747 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3750 fix(settings): use natural sorting
  src/settings/App.tsx
Labels: 3. to review

#3611 chore: update workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  lib/AppInfo/Application.php
  lib/Folder/FolderManager.php
  lib/Listeners/LoadAdditionalScriptsListener.php
  lib/Mount/GroupFolderStorage.php
  lib/Mount/GroupMountPoint.php
  lib/Mount/MountProvider.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  tests/Folder/FolderManagerTest.php
  tests/psalm-baseline.xml
Labels: 3. to review

#3758 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3760 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3759 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3761 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3751 fix(dav): only list top-level groupfolders
  lib/DAV/GroupFoldersHome.php
  src/services/groupfolders.ts
Labels: bug, 3. to review
