Repository nextcloud/groupfolders, pull requests merged in 2025-02, with the labels that each got.

#3579 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3578 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3580 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3543 fix: use owner instead of current user for move-to-trash logic
  lib/Trash/TrashBackend.php
Labels: backport-request, 3. to review

#3551 include circles to acl
  lib/ACL/UserMapping/IUserMapping.php
  lib/ACL/UserMapping/IUserMappingManager.php
  lib/ACL/UserMapping/UserMapping.php
  lib/ACL/UserMapping/UserMappingManager.php
  lib/Command/ListCommand.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/ResponseDefinitions.php
  openapi.json
  psalm.xml
  src/components/SharingSidebarView.vue
  src/settings/Api.ts
  src/settings/App.tsx
  src/types/index.ts
  src/types/openapi/openapi.ts
  tests/Folder/FolderManagerTest.php
  tests/stubs/oca_circles_ifederatedmodel.php
  tests/stubs/oca_circles_model_member.php
Labels: enhancement, 2. developing, feature: acl

#2960 fix(ACL): Add check to prevent users from revoking their own access
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/AppInfo/Application.php
  lib/DAV/ACLPlugin.php
  src/client.js
  tests/ACL/ACLManagerTest.php
Labels: enhancement, 3. to review

#3600 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3601 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3592 fix: catch some acl errors when listing trashbin
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3583 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3612 [stable30] allow to shallow scan
  appinfo/info.xml
  lib/Command/Scan.php
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#3620 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3623 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3622 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3618 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3621 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/Service/ApplicationService.php
Labels: dependencies, 3. to review

#3604 fix(trash): Fix deleting items from public share with write access
  lib/Trash/TrashBackend.php
Labels: 3. to review

#3627 [stable30] fix(trash): Fix deleting items from public share with write access
  lib/Trash/TrashBackend.php
Labels: bug, 3. to review

#3645 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3644 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3642 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3641 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3643 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3646 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
