Repository nextcloud/groupfolders, pull requests merged in 2025-03, with the labels that each got.

#3651 fix: add mount type to node info
  src/services/groupfolders.ts
Labels: bug, backport-request, 3. to review

#3661 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3660 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3684 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3682 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3683 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3681 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3699 fix(ACLPlugin): Use correct path to test new permissions
  lib/DAV/ACLPlugin.php
Labels: bug, backport-request, 3. to review

#3705 enh: Use Delete icon instead of Close icon
  src/components/SharingSidebarView.vue
Labels: 3. to review, design

#3696 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3709 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3694 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3710 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3695 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3720 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3721 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
