Repository nextcloud/groupfolders, pull requests merged in 2025-07, with the labels that each got.

#3874 fix(versions): Avoid new version entity if it exists on DB
  lib/Versions/GroupVersionsMapper.php
  lib/Versions/VersionsBackend.php
Labels: backport-request, 3. to review, version

#3882 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3889 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3892 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3894 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3893 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3895 feat: replace icons with outline versions
  img/app-dark.svg
  img/app.svg
  img/folder-group.svg
Labels: enhancement, 3. to review, design

#3898 [stable29] fix: don't error in getRelevantPaths if the root of the trash is passed
  lib/ACL/ACLManager.php
Labels: bug, 3. to review

#3902 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3903 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
