Repository nextcloud/groupfolders, pull requests merged in 2025-06, with the labels that each got.

#3815 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3814 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3813 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3816 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3817 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3834 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3832 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3837 fix: add `orderby` to pagination to prevent sorting issues
  lib/Controller/FolderController.php
  openapi.json
  src/settings/Api.ts
  src/settings/App.tsx
  src/types/openapi/openapi.ts
Labels: bug, backport-request, 3. to review

#3753 fix: don't error in getRelevantPaths if the root of the trash is passed
  lib/ACL/ACLManager.php
Labels: bug, 3. to review

#3831 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3856 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3857 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3859 build(composer): Stop updating vendor-bin when updating main composer.json
  composer.json
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: backport-request

#3851 [31] fix: only add storage to filecache join when sharding is used
  lib/Folder/FolderManager.php
  psalm.xml
  tests/stubs/oc_db_querybuilder_sharded_sharddefinition.php
Labels: 3. to review
