Repository nextcloud/groupfolders, pull requests merged in 2025-09, with the labels that each got.

#3943 refactor: remove more assumptions around groupfolder storage layout
  lib/AppInfo/Application.php
  lib/CacheListener.php
  lib/Command/ACL.php
  lib/Mount/CacheRootPermissionsMask.php
  lib/Mount/GroupMountPoint.php
  lib/Mount/MountProvider.php
  lib/Mount/RootPermissionsMask.php
Labels: 3. to review

#3956 Migrate to Material Symbols outline variant
  src/components/SharingSidebarView.vue
Labels: backport-request, 3. to review, design

#3961 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3963 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3964 [stable32] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3985 [stable32] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3982 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3984 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#4008 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3920 per groupfolder storage
  .github/workflows/phpunit-sqlite-s3.yml
  lib/Folder/FolderDefinition.php
  lib/Folder/FolderDefinitionWithMappings.php
  lib/Folder/FolderDefinitionWithPermissions.php
  lib/Folder/FolderManager.php
  lib/Folder/FolderWithMappingsAndCache.php
  lib/Mount/FolderStorageManager.php
  lib/Mount/MountProvider.php
  psalm.xml
  tests/Folder/FolderManagerTest.php
  tests/stubs/oc_files_objectstore_primaryobjectstoreconfig.php
Labels: 3. to review

#4012 feat: allow setting custom bucket for groupfolder during creation
  lib/Command/Create.php
  lib/Controller/FolderController.php
  lib/Folder/FolderManager.php
  lib/Mount/FolderStorageManager.php
  openapi.json
  src/types/openapi/openapi.ts
Labels: 3. to review

#4011 fix: ensure options is always an array
  lib/Folder/FolderManager.php
Labels: bug, 3. to review

#4021 Fix migration issue
  appinfo/info.xml
  lib/Migration/Version20001Date20250612140256.php
  lib/Migration/Version20002Date20250612140256.php
Labels: backport-request, 3. to review

#4024 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#4039 chore: improve Team Folders app description
  appinfo/info.xml
  openapi.json
Labels: enhancement, 3. to review
