Repository nextcloud/groupfolders, pull requests merged in 2025-05, with the labels that each got.

#3769 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3768 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3771 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3770 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3780 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3784 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3783 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3782 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3781 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3794 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3795 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3800 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3799 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3797 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3796 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3798 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3752 fix: prevent duplicate mount points
  lib/Command/Create.php
  lib/Command/Rename.php
  lib/Controller/FolderController.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/psalm-baseline.xml
Labels: bug, 3. to review

#3802 chore: suppress psalm for already asserted folder
  lib/Controller/FolderController.php
Labels: 3. to review, technical debt

#3805 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3806 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3807 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
