Repository nextcloud/groupfolders, pull requests merged in 2025-01, with the labels that each got.

#3509 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3515 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3390 perf: Add index for group_folders table
  appinfo/info.xml
  lib/Migration/Version19000Date20241029123147.php
Labels: backport-request, 3. to review, performance :rocket:

#3529 Release v19.0.0 alpha.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3533 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3532 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3535 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3508 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3536 chore: Rename app to Team folders
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  README.md
  appinfo/info.xml
  lib/Command/ACL.php
  lib/Command/Create.php
  lib/Command/Delete.php
  lib/Command/ExpireGroupVersionsPlaceholder.php
  lib/Command/Group.php
  lib/Command/ListCommand.php
  lib/Command/Quota.php
  lib/Command/Rename.php
  lib/Command/Scan.php
  lib/Command/Trashbin/Cleanup.php
  lib/DAV/ACLPlugin.php
  lib/Migration/Version104000Date20180918132853.php
  lib/Migration/Version201000Date20190111132839.php
  lib/Settings/Section.php
  lib/Trash/TrashBackend.php
  lib/Versions/VersionsBackend.php
  openapi.json
  src/actions/openGroupfolderAction.ts
  src/components/SharingSidebarView.vue
  src/init.ts
  src/settings/App.tsx
  templates/index.php
Labels: 3. to review

#3538 fix: Prefer mount owner over current user as owner of the storage
  lib/Mount/GroupFolderStorage.php
Labels: bug, backport-request, 3. to review

#3541 [stable30] fix: Prefer mount owner over current user as owner of the storage
  lib/Mount/GroupFolderStorage.php
Labels: bug

#3534 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/AuthorizedAdminSettingMiddleware.php
Labels: dependencies, 3. to review

#3547 docs: Add example for ACL with multiple groups
  README.md
  screenshots/acl.png
Labels: 3. to review, documentation

#3560 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3559 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3561 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3562 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3563 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3564 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3566 chore(deps): Update psalm to v6
  lib/CacheListener.php
  psalm.xml
  tests/Trash/TrashBackendTest.php
  tests/psalm-baseline.xml
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies: php, technical debt

#3570 refactor: Apply rector refactorings
  lib/ACL/ACLCacheWrapper.php
  lib/ACL/ACLManager.php
  lib/ACL/ACLManagerFactory.php
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/Rule.php
  lib/ACL/RuleManager.php
  lib/ACL/UserMapping/UserMapping.php
  lib/ACL/UserMapping/UserMappingManager.php
  lib/AppInfo/Application.php
  lib/AppInfo/Capabilities.php
  lib/AuthorizedAdminSettingMiddleware.php
  lib/BackgroundJob/ExpireGroupTrash.php
  lib/BackgroundJob/ExpireGroupVersions.php
  lib/CacheListener.php
  lib/Command/ACL.php
  lib/Command/Create.php
  lib/Command/ExpireGroup/ExpireGroupTrash.php
  lib/Command/ExpireGroup/ExpireGroupVersions.php
  lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php
  lib/Command/Group.php
  lib/Command/ListCommand.php
  lib/Command/Quota.php
  lib/Command/Scan.php
  lib/Command/Trashbin/Cleanup.php
  lib/Controller/FolderController.php
  lib/DAV/ACLPlugin.php
  lib/DAV/GroupFolderNode.php
  lib/DAV/GroupFoldersHome.php
  lib/DAV/RootCollection.php
  lib/Folder/FolderManager.php
  lib/Listeners/CircleDestroyedEventListener.php
  lib/Listeners/NodeRenamedListener.php
  lib/Migration/Version103000Date20180806161724.php
  lib/Migration/WrongDefaultQuotaRepairStep.php
  lib/Mount/CacheRootPermissionsMask.php
  lib/Mount/GroupFolderStorage.php
  lib/Mount/GroupMountPoint.php
  lib/Mount/MountProvider.php
  lib/Mount/RootPermissionsMask.php
  lib/Service/ApplicationService.php
  lib/Service/DelegationService.php
  lib/Service/FoldersFilter.php
  lib/Settings/Admin.php
  lib/Settings/Section.php
  lib/Trash/GroupTrashItem.php
  lib/Trash/TrashBackend.php
  lib/Trash/TrashManager.php
  lib/Versions/ExpireManager.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
  tests/ACL/ACLManagerTest.php
  tests/Folder/FolderManagerTest.php
Labels: 3. to review, technical debt
