Repository nextcloud/groupfolders, pull requests merged in 2025-08, with the labels that each got.

#3908 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3883 perf(FolderManager): Allow filtering getFoldersForUser by userId directly
  lib/Folder/FolderManager.php
  lib/Trash/TrashBackend.php
  tests/Folder/FolderManagerTest.php
Labels: 3. to review, performance :rocket:

#3923 [stable29] fix: Return folder id correctly after creating it
  src/settings/Api.ts
Labels: bug, 3. to review

#3917 [31] store the fileid of the root of groupfolders
  appinfo/info.xml
  lib/Folder/FolderManager.php
  lib/Migration/Version102020Date20180806161449.php
  lib/Migration/Version20000Date20250612140256.php
  lib/Mount/FolderStorageManager.php
  tests/Folder/FolderManagerTest.php
Labels: 3. to review

#3936 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#3937 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#3940 fix: make dropdown strings translatable
  src/settings/App.tsx
Labels: 3. to review

#3921 fix: make version backend storage location agnostic
  lib/AppInfo/Application.php
  lib/Mount/GroupMountPoint.php
  lib/Mount/MountProvider.php
  lib/Trash/TrashBackend.php
  lib/Versions/GroupVersion.php
  lib/Versions/GroupVersionsExpireManager.php
  lib/Versions/VersionsBackend.php
Labels: 3. to review

#3952 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
